-- Schema additions for the IDC Transfer Daemon.
--
-- Adds:
--   1. transfer_idc_file       — per-file snapshot table for an IDC transfer
--   2. notify_transfer_queued  — trigger function that fires on queue/re-queue
--   3. dataset_release_transfer_queued_notify — AFTER INSERT/UPDATE trigger
--
-- The existing transfer_status vocabulary on dataset_release_transfer is also
-- extended with 'in_progress' (used by the daemon while uploading). The column
-- is free text, so no DDL is required for that — documented here for the record.

BEGIN;

CREATE TABLE public.transfer_idc_file (
    transfer_idc_file_id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_release_transfer_id integer NOT NULL
        REFERENCES public.dataset_release_transfer(dataset_release_transfer_id) ON DELETE CASCADE,
    file_id                     integer NOT NULL
        REFERENCES public.file(file_id),
    gcs_url                     text    NOT NULL,  -- written by external fan-out as <base_path>/<md5>; the daemon never writes it
    status                      text    NOT NULL DEFAULT 'pending',
        -- 'pending' | 'completed' | 'failed'
    error                       text,              -- last error message
    attempts                    integer NOT NULL DEFAULT 0,
    updated_at                  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (dataset_release_transfer_id, file_id)  -- required for the fan-out's ON CONFLICT
);

-- Covers the producer's keyset pagination:
--   WHERE dataset_release_transfer_id = $1 AND status = 'pending'
--     AND transfer_idc_file_id > $last ORDER BY transfer_idc_file_id LIMIT 1000
CREATE INDEX ON public.transfer_idc_file (
    dataset_release_transfer_id, status, transfer_idc_file_id
);

CREATE OR REPLACE FUNCTION public.notify_transfer_queued()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.transfer_status = 'queued' THEN
        PERFORM pg_notify('idc_transfer_channel', NEW.dataset_release_transfer_id::text);
    END IF;
    RETURN NEW;
END;
$$;

-- Fires on INSERT and on transfer_status UPDATEs so that manually re-queuing
-- a failed transfer also wakes the daemon.
CREATE TRIGGER dataset_release_transfer_queued_notify
AFTER INSERT OR UPDATE OF transfer_status ON public.dataset_release_transfer
FOR EACH ROW EXECUTE FUNCTION public.notify_transfer_queued();

COMMIT;
